name: system_settings
description: Flutter plugin to open system and app settings on iOS and Android.
version: 2.1.0
homepage: https://github.com/fweinaug/system_settings
repository: https://github.com/fweinaug/system_settings

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.florianweinaug.system_settings
        pluginClass: SystemSettingsPlugin
      ios:
        pluginClass: SystemSettingsPlugin
